### ISSUE TITLE
Верстка ЛК с купленными курсами поехала

### ISSUE THREAD

**Issue by skatromb** [tough-dev-school/lms-frontend-v2#181]
![F42EC412-BB83-41FF-9C80-EF0E8B2E39C8](https://user-images.githubusercontent.com/1759463/215582019-f954e684-eb73-44a8-9658-76a533cb9e58.png)

**Comment by brachkow** [comment]
Блин https://bugs.webkit.org/show_bug.cgi?id=23113 сафари не умеет рендерить svg

**Comment by brachkow** [comment]
Теперь обложек на телефоне нет
