### ISSUE TITLE
В тёмной теме плохо видно шрифт конспектов

### ISSUE THREAD

**Issue by skatromb** [tough-dev-school/lms-frontend-v2#182]
![DCA4EFE2-F849-4AAC-8F6B-58A66CC2A95B](https://user-images.githubusercontent.com/1759463/215582527-1d88fef5-2323-4dc7-9611-d2445af055bf.png)

**Comment by brachkow** [comment]
Пофиксил, сейчас должно быть норм. Спасибо за репорт!
