### ISSUE TITLE
Migrate from vue3-notion to vue-notion

### ISSUE THREAD

**Issue by brachkow** [tough-dev-school/lms-frontend-v2#226]
Сейчас мы используем форк неофициального форка vue-notion под названием vue3-notion. Он работает, но содержит много багов и править их самим очень сложно из-за того как он написан.

Разработчик оригинального vue-notion делает его для Vue 3, но проект пока дошел только для альфы. Есть смысл на него перехать как он выйдет. Для того чтобы это не забылось я выношу это в ишью (в бейскемпе школы это тоже есть).

Следить за прогрессом vue-notion можно тут https://github.com/janniks/vue-notion/issues/38

**Comment by brachkow** [comment]
Я хочу попробовать мигрировать на альфу и посмотреть что будет, но не знаю когда у меня дойдут до этого руки

**Comment by janniks** [comment]
`beta` version released if you want to try it out 📦 `3.0.0-beta.1`
