### ISSUE TITLE
Не всегда подтягивается title Notion страницы

### ISSUE THREAD

**Issue by skhrvg** [tough-dev-school/lms-frontend-v2#240]
Сейчас из-за несовпадения material id из URL и идентификатора рендерируемой Notion страницы document.title не всегда обновляется.
Также, при навигации по странице через #hash, document.title сбрасывается роутер хуком.

> ![Снимок экрана 2023-05-23 в 11 42 12](https://github.com/tough-dev-school/lms-frontend-v2/assets/35118149/7072d998-9b64-465c-8d58-988cdef8a15a)

**Comment by f213** [comment]
Спасибо!
